spring:
  profiles.active: "shell"
  banner.location: "classpath:/banner.txt"

logging.level:
  root: "INFO"
  ru.otus.springframework.quiz.Main: "WARN"

quiz:
  locale: "en-US"

  i18n:
    auth:
      bundle: "i18n/auth/auth_msg"
      first-name: "auth.first.name"
      last-name: "auth.last.name"

    report.bundle: "i18n/report/report_msg"

    question:
      bundle: "i18n/question/questions"
      path: "questions.csv.path"