library:
  dao.provider: "spring-jpa"
  db:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "password123"

spring:
  datasource:
    url: ${library.db.url}
    username: ${library.db.username}
    password: ${library.db.password}
  data.mongodb.repositories.type: NONE
