library:
  prompt: "library:>"
  dao.provider: "spring-jpa"

spring:
  banner.location: "classpath:/banner.txt"
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"

logging.level:
  root: "WARN"


