library.dao.provider: "spring-reactive-mongodb-jpa"

spring:
  shell.interactive.enabled: "false"
  thymeleaf.cache: "false"
  thymeleaf.prefix: "classpath:/templates-rest/"
  main.web-application-type: "REACTIVE"

