library:
  prompt: "library:>"

spring:
  profiles.active:
      - "mongodb"
      - "flux"
  banner.location: "classpath:/banner.txt"
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"

logging.level:
  root: "INFO"
  ru.otus: "DEBUG"

