version: "3"

services:

  mongodb:
    image: mongo:latest
    container_name: "mongodb"

  library:
    image: otusspring201811slobanov/l06-library-service
    environment:
      - "DB_URL=mongodb://mongodb:27017"
    links:
      - "mongodb"
    ports:
      - 8080:8080